import type { WorkItem } from '@/domain/work-items/work-item';

const shiftHours = (date: Date, hours: number) =>
  new Date(date.getTime() + hours * 3_600_000).toISOString();

export function createMockWorkItems(now = new Date()): WorkItem[] {
  return [
    {
      id: 'sf-1048',
      externalId: 'CASE-1048',
      source: 'salesforce',
      title: 'Acesso bloqueado para cliente',
      description:
        'Cliente não consegue acessar o portal após a redefinição de senha.',
      status: 'new',
      priority: 'critical',
      assignee: 'Marcelo Santos',
      customer: 'ACME Brasil',
      createdAt: shiftHours(now, -8),
      updatedAt: shiftHours(now, -0.2),
      dueAt: shiftHours(now, 0.45),
      externalUrl: 'https://example.com/salesforce/CASE-1048',
    },
    {
      id: 'jira-1429',
      externalId: 'SP-1429',
      source: 'jira',
      title: 'Validar regra de faturamento',
      description:
        'Confirmar o comportamento da regra para contratos com renovação automática.',
      status: 'in_progress',
      priority: 'high',
      assignee: 'Marcelo Santos',
      customer: 'Orbe Tecnologia',
      createdAt: shiftHours(now, -30),
      updatedAt: shiftHours(now, -2),
      dueAt: shiftHours(now, 3.2),
      externalUrl: 'https://example.com/jira/SP-1429',
    },
    {
      id: 'mail-889',
      externalId: 'MAIL-889',
      source: 'email',
      title: 'Responder solicitação de evidências',
      description:
        'O time financeiro solicitou comprovantes do processamento de ontem.',
      status: 'waiting',
      priority: 'high',
      assignee: 'Marcelo Santos',
      customer: 'Financeiro interno',
      createdAt: shiftHours(now, -18),
      updatedAt: shiftHours(now, -6),
      dueAt: shiftHours(now, 6),
      externalUrl: 'https://example.com/email/MAIL-889',
    },
    {
      id: 'jira-1408',
      externalId: 'SP-1408',
      source: 'jira',
      title: 'Revisar documentação da integração',
      description:
        'Revisar o passo a passo de configuração antes da publicação.',
      status: 'new',
      priority: 'medium',
      assignee: 'Ana Lima',
      customer: 'Nimbus',
      createdAt: shiftHours(now, -52),
      updatedAt: shiftHours(now, -9),
      dueAt: shiftHours(now, 28),
      externalUrl: 'https://example.com/jira/SP-1408',
    },
    {
      id: 'sf-1039',
      externalId: 'CASE-1039',
      source: 'salesforce',
      title: 'Divergência no relatório mensal',
      description:
        'Totais do relatório não coincidem com o fechamento informado pelo cliente.',
      status: 'in_progress',
      priority: 'high',
      assignee: 'Marcelo Santos',
      customer: 'Vega Comércio',
      createdAt: shiftHours(now, -26),
      updatedAt: shiftHours(now, -4),
      dueAt: shiftHours(now, 15),
      externalUrl: 'https://example.com/salesforce/CASE-1039',
    },
    {
      id: 'mail-874',
      externalId: 'MAIL-874',
      source: 'email',
      title: 'Confirmar janela de manutenção',
      description:
        'Responder com a confirmação da janela sugerida para sábado.',
      status: 'new',
      priority: 'medium',
      assignee: 'Marcelo Santos',
      customer: 'Horizonte Saúde',
      createdAt: shiftHours(now, -10),
      updatedAt: shiftHours(now, -3),
      dueAt: shiftHours(now, 22),
      externalUrl: 'https://example.com/email/MAIL-874',
    },
    {
      id: 'jira-1391',
      externalId: 'SP-1391',
      source: 'jira',
      title: 'Investigar lentidão na consulta',
      description:
        'A consulta de contratos apresenta lentidão em horários de pico.',
      status: 'waiting',
      priority: 'low',
      assignee: 'João Alves',
      customer: 'Atlas Logística',
      createdAt: shiftHours(now, -72),
      updatedAt: shiftHours(now, -20),
      dueAt: shiftHours(now, 48),
      externalUrl: 'https://example.com/jira/SP-1391',
    },
    {
      id: 'sf-1021',
      externalId: 'CASE-1021',
      source: 'salesforce',
      title: 'Confirmar ajuste de cadastro',
      description: 'A alteração foi validada e comunicada ao cliente.',
      status: 'resolved',
      priority: 'medium',
      assignee: 'Marcelo Santos',
      customer: 'Delta Serviços',
      createdAt: shiftHours(now, -48),
      updatedAt: shiftHours(now, -1),
      externalUrl: 'https://example.com/salesforce/CASE-1021',
    },
    {
      id: 'mail-861',
      externalId: 'MAIL-861',
      source: 'email',
      title: 'Orientação sobre novo usuário',
      description: 'Instruções de primeiro acesso enviadas ao solicitante.',
      status: 'resolved',
      priority: 'low',
      assignee: 'Marcelo Santos',
      customer: 'Aurora Educação',
      createdAt: shiftHours(now, -36),
      updatedAt: shiftHours(now, -5),
      externalUrl: 'https://example.com/email/MAIL-861',
    },
  ];
}
